---
proxy-providers:
  Browsing:
    type: file
    path: "./proxy_provider/browsing.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Olshop:
    type: file
    path: "./proxy_provider/olshop.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Sosmed:
    type: file
    path: "./proxy_provider/sosmed.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Tiktok:
    type: file
    path: "./proxy_provider/tiktok.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Whatsapp:
    type: file
    path: "./proxy_provider/whatsapp.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Gaming:
    type: file
    path: "./proxy_provider/gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: Browsing
  type: load-balance
  disable-udp: false
  use:
  - Browsing
- name: Olshop
  type: load-balance
  disable-udp: false
  use:
  - Olshop
- name: Sosmed
  type: load-balance
  disable-udp: false
  use:
  - Sosmed
- name: Tiktok
  type: load-balance
  disable-udp: false
  use:
  - Tiktok
- name: Whatsapp
  type: load-balance
  disable-udp: false
  use:
  - Whatsapp
- name: Gaming
  type: load-balance
  disable-udp: false
  use:
  - Gaming
rule-providers:
  Direct:
    type: file
    behavior: classical
    path: "./rule_provider/direct.yaml"
  Reject:
    type: file
    behavior: classical
    path: "./rule_provider/reject.yaml"
  Browsing:
    type: file
    behavior: classical
    path: "./rule_provider/browsing.yaml"
  Olshop:
    type: file
    behavior: classical
    path: "./rule_provider/olshop.yaml"
  Sosmed:
    type: file
    behavior: classical
    path: "./rule_provider/sosmed.yaml"
  Whatsapp:
    type: file
    behavior: classical
    path: "./rule_provider/whatsapp.yaml"
  Youtube:
    type: file
    behavior: classical
    path: "./rule_provider/youtube.yaml"
  Tiktok:
    type: file
    behavior: classical
    path: "./rule_provider/tiktok.yaml"
  Gaming:
    type: file
    behavior: classical
    path: "./rule_provider/gaming.yaml"
rules:
- RULE-SET,Browsing,Browsing
- RULE-SET,Olshop,Olshop
- RULE-SET,Sosmed,Sosmed
- RULE-SET,Youtube,DIRECT
- RULE-SET,Tiktok,Tiktok
- RULE-SET,Whatsapp,Whatsapp
- RULE-SET,Gaming,Gaming
- MATCH,Browsing,Olshop,Sosmed,Youtube,Tiktok,Whatsapp,Gaming
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: reyre
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: false
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
ipv6: false
profile:
  store-selected: true
tproxy-port: 7895
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53

